### ISSUE TITLE
undefined furniture request.

### ISSUE THREAD

**Issue by alexislours** [modunogay/modunogay.github.io#1]
Hi,
I'm receiving quite a few calls from your site with the furniture image id as undefined(~200/days).
Might want to check in on your loops.
eg:
![image](https://user-images.githubusercontent.com/37421461/83215414-30c2d600-a167-11ea-8175-2f7ffd7e1b9a.png)

**Comment by modunogay** [comment]
I'm very sorry about that.
I'll review it now.

**Comment by modunogay** [comment]
I have changed  it
I sincerely apologize for the mistake.
